# ctrl-b [HJKL] expand pane
bind -r H resize-pane -L 1
bind -r J resize-pane -D 1
bind -r K resize-pane -U 1
bind -r L resize-pane -R 1

# ctrl-b ctrl-b to switch panes to the last pane
bind C-b if-shell -F "#{window_zoomed_flag}" "select-pane -t ! \; resize-pane -Z" "select-pane -t !"

# turn on mouse clicks
set -g mouse on
